### ISSUE TITLE
niter: make larger?

### ISSUE THREAD

**Issue by keflavich** [ACES-CMZ/reduction_JACKS#11]
https://github.com/ACES-CMZ/reduction_JACKS/blob/7bdc19e28c24d3183792389d8a7f08731560480f/pipeline_scripts/scriptForImaging_JACKS_CONT.py#L90

niter=2000 is very small; I'd recommend increasing it to something huge and letting the threshold be the stopping criterion

**Comment by xinglunju** [comment]
Yes, it is small... I used a small number for niter to prodce a first-look image. Once we sort out how to flag spectral lines, do selfcal, and probably incorporate the wide-field imaging, then we can try a larger number.
